FROM scratch as placeholder

ARG version
LABEL org.opencontainers.image.version=${version}
RUN <<EORUN
set -eu
dnf -y update --no-docs
dnf -y clean all
rm -rf /var/log/*
rm -rf /var/cache/*
rm -rf /var/tmo/*
EORUN